 create sequence S_CONTROL_ERRORES
  start with 1
  increment by 1
  maxvalue 99999999999999999
  minvalue 1
/
drop sequence s_control_errores;
/
SET SERVEROUTPUT ON
BEGIN
    DBMS_OUTPUT.PUT_LINE(S_CONTROL_ERRORES.CURRVAL);
END;
/
CREATE TABLE CONTROL_ERRORES(
    ID NUMBER,
    USUARIO VARCHAR2(100),
    MENSAJE VARCHAR2(200),
    COMANDO VARCHAR2(1000),
    FECHAR DATE
);
/
describe control_errores
/
rollback
/
drop table CONTROL_ERRORES;
/
select * from all_objects where object_type like 'TRIGGER' and object_name like 'T_C%'
/
CREATE OR REPLACE TRIGGER T_CONTROL_ERRORES 
AFTER SERVERERROR
ON DATABASE
DECLARE 
    SQL_TEXT ora_name_list_t;
    MENSAJE VARCHAR2(1000):= NULL;
    COMANDO VARCHAR2(1000):=NULL;
    ID NUMBER;
BEGIN
    FOR I IN 1..ORA_SERVER_ERROR_DEPTH LOOP
        MENSAJE := I||' -> '||MENSAJE||' | '||ORA_SERVER_ERROR_MSG(I);
    END LOOP;
    FOR I IN 1..ORA_SQL_TXT(SQL_TEXT) LOOP
        COMANDO := COMANDO||SQL_TExT(I); 
    END LOOP;
    ID := S_CONTROL_ERRORES.NEXTVAL;
    INSERT INTO CONTROL_ERRORES VALUES(ID, ORA_LOGIN_USER, MENSAJE, COMANDO,SYSDATE);
END;
/
DESC ORA_NAME_LIST_T
/

begin
SELECT * FROM XXXXXXXXXX;
end;
/
SELECT * FROM CONTROL_ERRORES
/
DELETE FROM CONTROL_ERRORES