CREATE TABLE HR.HORA (
ACCION DATE
);
/
CREATE OR REPLACE PROCEDURE MI_ACCION IS
    BEGIN
        INSERT INTO HR.HORA(ACCION) VALUES (SYSDATE);
    END;
/
BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        JOB_NAME => 'ACCION1',
        JOB_TYPE => 'STORED_PROCEDURE',
        JOB_ACTION => 'MI_ACCION',
        START_DATE => '16-OCT-19 07.00.00 PM',
        REPEAT_INTERVAL => 'FREQ=SECONDLY;INTERVAL=10',
        END_DATE => '17-OCT-19 07.00.00 PM',
        AUTO_DROP => FALSE,
        COMMENTS => 'MI NUEVA ACCION');
END ;
    
/
SELECT * FROM ALL_OBJECTS WHERE UPPER(OBJECT_NAME) LIKE '%ACCION%'
/
EXEC DBMS_SCHEDULER.disable('ACCION1');
/
EXEC DBMS_SCHEDULER.ENABLE('ACCION1');
/
DELETE HR.HORA
/
SELECT * FROM HR.HORA