SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE obtenerSalarioEmpleado(SALARIO NUMBER) IS 
	TYPE EMPLEADO IS VARRAY(1000) OF HR.EMPLOYEES%ROWTYPE;
	EMPLEADOS EMPLEADO := EMPLEADO();
BEGIN
	BEGIN
		SELECT * BULK COLLECT INTO EMPLEADOS 
		  FROM HR.EMPLOYEES 
		 WHERE SALARY > SALARIO;
	EXCEPTION WHEN NO_DATA_FOUND THEN EMPLEADOS := NULL;
	END;

    DBMS_OUTPUT.PUT_LINE('EL NUMERO DE EMPLEADOS CARGADO ES DE: '||EMPLEADOS.COUNT());
    
    DBMS_OUTPUT.PUT_LINE('----------------------------------------------------------');
    
	FOR I IN 1..EMPLEADOS.COUNT() LOOP
		DBMS_OUTPUT.PUT_LINE('NOMBRE: '||EMPLEADOS(I).FIRST_NAME||' APELLIDO: '||EMPLEADOS(I).LAST_NAME||' SU SALARIO ES: '||EMPLEADOS(I).SALARY);
	END LOOP;
END;

EXECUTE obtenerSalarioEmpleado(20000);