CREATE OR REPLACE PACKAGE paq1 
AS
	TYPE C_VARIABLE IS REF CURSOR;
	FUNCTION miFuncion(c1 in out C_VARIABLE, X NUMBER) RETURN VARCHAR2;
END;
/
CREATE OR REPLACE PACKAGE BODY paq1 
AS
	FUNCTION miFuncion(c1 in out C_VARIABLE, X NUMBER) RETURN VARCHAR2 IS
	EMPLEADOS EMPLOYEES%ROWTYPE;
	DEPARTAMENTOS DEPARTAMENTS%ROWTYPE;
	BEGIN
		IF X=1 THEN
			OPEN c1 FOR SELECT * FROM EMPLEADOS;
			FETCH c1 INTO EMPLEADOS;
		ELSE
			OPEN c1 FOR SELECT * FROM DEPARTAMENTS;
			FETCH c1 INTO DEPARTAMENTOS;
		END IF;
	END;
END;
/


