CREATE OR REPLACE PACKAGE paq1 
AS
	TYPE C_VARIABLE IS REF CURSOR;
	FUNCTION miFuncion(c1 in out C_VARIABLE, X NUMBER) RETURN VARCHAR2;
END;
/
CREATE OR REPLACE PACKAGE BODY paq1 
AS
	FUNCTION miFuncion(c1 in out C_VARIABLE, X NUMBER) RETURN VARCHAR2 IS
	EMPLEADOS HR.EMPLOYEES%ROWTYPE;
	DEPARTAMENTOS HR.DEPARTMENTS%ROWTYPE;
	BEGIN
		IF X=1 THEN
			OPEN c1 FOR SELECT * FROM HR.EMPLOYEES;
			FETCH c1 INTO EMPLEADOS;
            RETURN EMPLEADOS.first_name;
		ELSE
			OPEN c1 FOR SELECT * FROM HR.DEPARTMENTS;
			FETCH c1 INTO DEPARTAMENTOS;
            RETURN DEPARTAMENTOS.department_name;
		END IF;
	END;
END;
/

SET SERVEROUTPUT ON
DECLARE
    DATOS paq1.C_VARIABLE;
BEGIN
    DBMS_OUTPUT.PUT_LINE(paq1.miFuncion(DATOS,2));
END;