desc HR.locations

DECLARE
	c1 SYS_REFCURSOR;
	REGIONES HR.REGIONS%ROWTYPE;
    LOCALIDADES HR.locations%ROWTYPE;
BEGIN
	OPEN c1 FOR SELECT * FROM HR.REGIONS;
	FETCH c1 INTO REGIONES;
	CLOSE c1;
    OPEN c1 FOR SELECT * FROM HR.locations;
    FETCH c1 INTO LOCALIDADES;
    CLOSE c1;

    DBMS_OUTPUT.PUT_LINE('Region: '||REGIONES.REGION_NAME||' Localidad: '||LOCALIDADES.CITY);
    
END;